#!/usr/bin/env bash

## Description: Setup Umami for searching
## Usage: umami [flags] [args]
## Example: "ddev umami"
## ExecRaw: true

set -eu -o pipefail

drush si demo_umami
drush recipe ../recipes/scolta_umami
drush scolta:build --force
